import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import "animate.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";

import NavBarComponent from "./components/NavBar/NavBarComponent";
import ContactUsComponent from "./components/contact/ContactUsComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <body className={inter.className}>
        <NavBarComponent></NavBarComponent>
        <div className="page-box">{children}</div>
        <ContactUsComponent />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossorigin="anonymous"
        />
      </body>
    </html>
  );
}
